[global]
repo1-path=/var/lib/pgbackrest
log-path=/var/log/pgbackrest
log-level-console=info
log-level-file=detail
start-fast=y

[localforge]
pg1-path=/var/lib/postgresql/18/docker
pg1-port=5432
pg1-socket-path=/var/run/pgsocket
pg1-user=localforge_app
pg1-database=localforge
