# Generated by Django 6.0.8 on 2026-09-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginThrottleEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bucket", models.CharField(max_length=160)),
                ("request_id", models.CharField(max_length=80)),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "db_table": "accounts_login_throttle_event",
                "indexes": [
                    models.Index(
                        fields=["bucket", "occurred_at"], name="accounts_login_bucket_time"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bucket", "request_id"), name="accounts_login_bucket_request_unique"
                    )
                ],
            },
        ),
    ]
