# Generated by Django 6.0.8 on 2026-09-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_loginthrottleevent"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="loginthrottleevent",
            index=models.Index(fields=["occurred_at", "id"], name="accounts_login_occurred_id"),
        ),
    ]
