global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus-pm5db:9090"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor-cv8mh:8080"]

  - job_name: postgres-primary
    static_configs:
      - targets: ["postgres-exporter-pe4rk:9187"]

  - job_name: postgres-standby
    metrics_path: /probe
    params:
      auth_module: ["standby"]
    static_configs:
      - targets: ["postgres-replica-pg6vy:5432"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter-pe4rk:9187

  - job_name: rabbitmq
    static_configs:
      - targets: ["rabbitmq-rq4sx:15692"]

  - job_name: valkey-cache
    static_configs:
      - targets: ["valkey-cache-exporter-ve7ts:9121"]

  - job_name: valkey-channels
    static_configs:
      - targets: ["valkey-channels-exporter-vx4nq:9121"]

  - job_name: loki
    static_configs:
      - targets: ["loki-lk3ny:3100"]

  - job_name: alloy
    static_configs:
      - targets: ["alloy-al6wz:12345"]

  - job_name: django
    static_configs:
      - targets: ["django-metrics-nb4xt:8001"]
