# Generated by Django 6.0.8 on 2026-09-16 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_login_throttle_retention_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(null=True)),
                ("delivery_claimed_at", models.DateTimeField(null=True)),
                ("delivered_at", models.DateTimeField(null=True)),
                ("subject_id", models.UUIDField()),
                (
                    "account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activation_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-issued_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["subject_id", "used_at"],
                        name="accounts_activation_subject_used",
                    ),
                    models.Index(
                        fields=["issued_at", "id"],
                        name="accounts_activation_issued_id",
                    ),
                ],
            },
        ),
    ]
