# Generated by Django 6.0.8 on 2026-09-18 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_usernameresettoken"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="activationtoken",
            new_name="accounts_act_subject_used",
            old_name="accounts_activation_subject_used",
        ),
    ]
