entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: false
    http:
      aliasHeadersStrategy: delete
      encodedCharacters:
        allowEncodedSlash: false
        allowEncodedBackSlash: false
        allowEncodedNullCharacter: false
        allowEncodedSemicolon: false
        allowEncodedPercent: false
        allowEncodedQuestionMark: false
        allowEncodedHash: false

  dashboard:
    address: ":8080"
    http:
      aliasHeadersStrategy: delete
      encodedCharacters:
        allowEncodedSlash: false
        allowEncodedBackSlash: false
        allowEncodedNullCharacter: false
        allowEncodedSemicolon: false
        allowEncodedPercent: false
        allowEncodedQuestionMark: false
        allowEncodedHash: false

  health:
    address: ":8082"

api:
  dashboard: true
  insecure: false

ping:
  entryPoint: health

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: edge-net-ne2vk
    watch: true

accessLog:
  format: json
  addInternals: true

log:
  level: INFO
  format: json

global:
  checkNewVersion: false
  sendAnonymousUsage: false
